site_name: Hello, I’m Anuj 👋
site_description: Anuj Khandelwal's Personal Website

theme:
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  name: material
  font:
    text: Epilogue
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/regular/bookmark
      info: octicons/info-16
      tip: material/fire
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: octicons/zap-16
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    primary: black
  
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    - toc.integrate
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anujonthemove/
    
    - icon: fontawesome/brands/medium
      link: https://www.medium.anujonthemove.com/
    
    - icon:  fontawesome/brands/github
      link: https://github.com/anujonthemove
    
  generator: false

plugins: []


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  # - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # The BetterEm extension improves the detection of Markup to emphasize text in Markdown using special characters
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  
  - toc:
      toc_depth: 0



nav:
  - About Me: 'index.md'
  - 'My Experience': 
    - 'Advanced Driver Assistance Systems (ADAS)': 'advanced-driver-assistance-systems.md'
    - 'Applied Machine Learning': 'applied-machine-learning.md'
    - 'Big Data' : 'big-data.md'
    - 'Computer Vision': 'computer-vision.md'
    - 'Internet of Things(IoT)': 'internet-of-things.md'
    - 'Hardware Configuration': 'hardware-configuration.md'
    - 'Software Engineering': 'software-engineering.md'
    
    